# Generated by Django 2.0.3 on 2019-02-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='large',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sicilian',
            field=models.BooleanField(default=False),
        ),
    ]
