# Generated by Django 2.0.3 on 2019-02-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190210_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='PizzaPrice',
        ),
    ]
