# Generated by Django 2.0.3 on 2019-02-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190210_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterUniqueTogether(
            name='pizzaprice',
            unique_together={('sicilian', 'large', 'toppings_count')},
        ),
    ]
