# Generated by Django 2.0.3 on 2019-03-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190217_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatter',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='dinnerplatter',
            unique_together={('name', 'large')},
        ),
    ]
