# Generated by Django 2.0.3 on 2019-03-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_addons_food_order_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Dinner Platter', 'Dinner Platter'), ('Sub', 'Sub'), ('Dinner', 'Dinner'), ('Pasta', 'Pasta'), ('Salad', 'Salad')], max_length=32),
        ),
    ]
