# Generated by Django 2.0.3 on 2019-04-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190326_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
